# Generated by Django 3.1 on 2020-12-18 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductcodePriceAPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BR_Code', models.CharField(max_length=20)),
                ('P_Code', models.CharField(max_length=20)),
                ('MRP', models.IntegerField(max_length=20)),
                ('Sale_Rate', models.IntegerField(max_length=20)),
                ('Discount', models.CharField(max_length=20)),
                ('Brand', models.CharField(max_length=20)),
            ],
        ),
    ]
