# Generated by Django 3.1 on 2020-12-19 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retailerapi', '0004_remove_productcodeprice_balancequantity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductcodePrice',
            new_name='productcodepriceapi',
        ),
    ]
