# Generated by Django 3.1 on 2020-12-26 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retailerapi', '0006_productcodepriceapi_balancequantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='productrevenuedeatils_paymentmode',
        ),
    ]
