# Generated by Django 3.1 on 2020-12-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailerapi', '0007_delete_productrevenuedeatils_paymentmode'),
    ]

    operations = [
        migrations.CreateModel(
            name='productrevenuedeatils_paymentmode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BR_Code', models.CharField(max_length=20)),
                ('TransactionNumber', models.IntegerField(max_length=20)),
                ('SaleAmount', models.IntegerField(max_length=20)),
                ('Narration', models.IntegerField(max_length=20)),
            ],
        ),
    ]
