# Generated by Django 3.1 on 2020-12-26 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retailerapi', '0008_productrevenuedeatils_paymentmode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productrevenuedeatils_paymentmode',
            name='Narration',
        ),
    ]
