# Generated by Django 3.1 on 2020-12-26 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailerapi', '0009_remove_productrevenuedeatils_paymentmode_narration'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrevenuedeatils_paymentmode',
            name='Narration',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
